CREATE TABLE IF NOT EXISTS USER_POST (
    POST_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    BIO TEXT,
    FOLLOWERS_COUNT INT,
    FOLLOWING_COUNT INT,
    PROFILE_PICTURE VARCHAR(255),
    ACCOUNT_CREATION_DATE TIMESTAMP,
    POST_TIMESTAMP TIMESTAMP,
    CAPTION TEXT,
    LIKES_COUNT INT,
    COMMENTS_COUNT INT,
    POST_TYPE VARCHAR(255),
    HASHTAGS VARCHAR(255),
    MENTIONS VARCHAR(255),
    ENGAGEMENT_RATE DOUBLE
);

CREATE TABLE IF NOT EXISTS SPOTIFY_DATA (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SIGNUP_DATE DATE,
    LAST_ACTIVE_DATE DATE,
    SUBSCRIPTION_TYPE VARCHAR(255),
    SUBSCRIPTION_STATUS VARCHAR(255),
    CHURN INT,
    TOTAL_PLAYTIME INT,
    TOTAL_SONGS_PLAYED INT,
    AVERAGE_SESSION_LENGTH INT,
    PLAYLISTS_CREATED INT,
    LIKED_SONGS_COUNT INT,
    SKIP_RATE DOUBLE
);

CREATE TABLE IF NOT EXISTS TWEET (
    TWEET_ID BIGINT NOT NULL PRIMARY KEY ,
    USER_ID BIGINT NOT NULL,
    TWEET_TIMESTAMP TIMESTAMP ,
    TWEET_TEXT VARCHAR(255),
    RETWEETS_COUNT INT,
    LIKES_COUNT INT,
    REPLIES_COUNT INT,
    HASHTAGS VARCHAR(255),
    MENTIONS VARCHAR(255),
    MEDIA_TYPE VARCHAR(50),
    SENTIMENT VARCHAR(50)
);

